---
javascripts:
- base:
  - rails
  - jquery.tools.min
  - jquery-ui
  - jquery.textarea
  - jquery.autocomplete
  - jquery.fcbkcomplete
  - jquery.notifyBar
  - jquery.hotkeys
  - jquery.autoSuggest
  - showdown
  - application
  - modules/sessions
  - modules/retag
  - modules/new_question
  - modules/show_user
  - modules/members
  - modules/move_group

- show:
  - MathJax/mathjax/MathJax
  - wmd/jquery.wmd
  - wmd/jquery.wmd.mathjax
  - modules/single/question
  - modules/show_question

stylesheets:
- base:
  - jquery-ui
  - compiled/application
  - search
- landing:
  - compiled/landing

