---
javascripts:
- base:
  - rails
  - jquery.tools.min
  - jquery-ui
  - jquery.textarea
  - jquery.notifyBar
  - jquery.hotkeys
  - showdown
  - autocompleteBox
  - application
  - modules/sessions
  - modules/index_question
  - modules/retag
  - modules/new_question
  - modules/show_user

- show:
  - MathJax/mathjax/MathJax
  - wmd/jquery.wmd
  - wmd/jquery.wmd.mathjax
  - modules/single/question
  - jquery.autovideo
  - modules/show_question

stylesheets:
- base:
  - jquery-ui
  - compiled/application
  - search
- landing:
  - compiled/landing

