---
javascripts:
- base:
  - jquery
  - jquery.tools.min
  - jquery-ui
  - jquery.textarea
  - jquery.autocomplete
  - jquery.fcbkcomplete
  - jquery.notifyBar
  - showdown
  - highlight/prettify
  - components/search
  - application
  - modules/sessions
  - modules/index_question
  - modules/retag
  - modules/new_question
  - modules/index_welcome
  - modules/show_user
  - modules/index_group
  - modules/index_user
  - modules/tags_question
  - modules/members
  - modules/move_group

- show:
  - MathJax/mathjax/MathJax
  - wmd/jquery.wmd.min
  - wmd/jquery.wmd.mathjax
  - modules/single/question
  - jquery.autovideo
  - modules/show_question

stylesheets:
- base:
  - jquery-ui
  - compiled/application
  - prettify

